language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
before_install:
  - pip install -e .
  # Test api script
  - api --help
  - api simple --help
  - api ioc --help

# command to run tests
script:
  - nosetests
