language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
# command to install dependencies
before_install:
  - pip install -e .[server]
  # Test api script
  - api --help
  - api simple --help
  - api ioc --help
  - pip install nose coverage

# command to run tests
script:
  - nosetests --with-coverage --cover-package=tb_api

