requirements: []

#imports:
#  - resource: 'settings.yml'

parameters:
#  API_ModuleSuffix: Service
#  API_AppHandler:
#    - FlaskCrossDomain
#    - FlaskLogin
  API_CORS:
    "/api/*": {"origins": "*"}


  API_Config:
    paths:
      "clients":
        tags: [Client]
        get:
          method: $ClientService.list
          summary: Get list clients
        post:
          method: $ClientService.create
          summary: Create new client
          fields:
            - name: name
              description: Client Name
      "clients/{client_id:int}":
        tags: [Client]
        get:
          method: $ClientService.get_by_id
          summary: Get client info
          fields:
            - name: client_id
              description: Client ID


services:
  Login: flask_login.login_required
  ClientService:
    class: my_package.client.ClientService
